export const USER_ROLES = {
  ROLE_LOCAL_MANAGER: 'ROLE_LOCAL_MANAGER',
  ROLE_LOCAL_USER: 'ROLE_LOCAL_USER',
  ROLE_CENTRAL_MANAGER: 'ROLE_CENTRAL_MANAGER',
  ROLE_CENTRAL_USER: 'ROLE_CENTRAL_USER',
}

export const MODEL_BASE_MODE = {
  LOCAL: 'LOCAL',
  CENTRAL: 'CENTRAL',
  UNAUTHORIZED: 'UNAUTHORIZED',
}